### ISSUE TITLE
Fix installation instructions

### ISSUE THREAD

**Issue by johnbradley** [Imageomics/kabr-tools#60]
When installing kabr-tools in a clean environment as described in the README:
```
pip install git+https://github.com/Imageomics/kabr-tools
```
The following error occurs:
```
...
Collecting detectron2@ git+https://github.com/facebookresearch/detectron2.git@2a420edb307c9bdf640f036d3b196bed474b8593 (from kabr_tools==0.1.0)
...
ModuleNotFoundError: No module named 'torch'
```

**Comment by zhong-al** [comment]
Can you check if [enhancement/setuptools](https://github.com/Imageomics/kabr-tools/tree/enhancement/setuptools) fixes this? `python -m pip install git+https://github.com/Imageomics/kabr-tools@138d170e7b5ed9ce76b3846d2f01b8d015cfa608` works for me.

**Comment by johnbradley** [comment]
@zhong-al After deleting the `~/.cache` directory install from this branch still fails for me. Even adding 'torch' to `build-system.requires` in addition to your changes doesn't fix the issue. I think instead we need to update the README to include two steps for installation of the software: 1) Install pytorch 2) install kabr-tools. We could reference the detectron2 Requirements in our README:https://detectron2.readthedocs.io/en/latest/tutorials/install.html#requirements. Alternatively we could  referencing the pytorch documentation: https://pytorch.org/get-started/locally/. On the pytorch page users can pick the version of CUDA  and other options based on their environment.

**Comment by zhong-al** [comment]
@johnbradley I updated the instructions [here](https://github.com/Imageomics/kabr-tools/blob/enhancement/install-instructions/README.md). I can update it again if it doesn't fix the issue.

**Comment by johnbradley** [comment]
@zhong-al These instructions look good to me. The instructions worked fine for me using pip within a conda environment on my Mac.

I still had a problem trying to use `uv pip` after deleting `~/.cache/uv/`, but I think that's a problem with uv: https://github.com/astral-sh/uv/issues/2252.

I would close the setuptools PR - there are quite a few more changes necessary to switch over to setuptools. Since it doesn't fix this issue I'm not aware of any advantage we would get to switching from hatch to setuptools.
