### ISSUE TITLE
make kabr_tools a python package 

### ISSUE THREAD

**Issue by jennamk14** [Imageomics/kabr-tools#9]
Make scripts accessible as a package for enhanced usability

**Comment by zhong-al** [comment]
@jennamk14 @egrace479 is this issue resolved by #22 #23 #31 ?

**Comment by jennamk14** [comment]
> @jennamk14 @egrace479 is this issue resolved by #22 #23 #31 ?

Yes, i believe so. @egrace479 do you agree? thanks!
